### ISSUE TITLE
422 Error for Autocomplete 

### ISSUE THREAD

**Issue by dan714** [lob/address-elements#3]
Hello there,

We are consumers of Lob's autocomplete API. It no longer seems to be working... We are seeing this being returned. Looks related to some changes merged today?

```
{
    "error": {
        "message": "av_elements_origin is not allowed",
        "status_code": 422,
        "code": "invalid"
    }
}
```

**Comment by dan714** [comment]
@mmrtnz Can we get some help here?

**Comment by mmrtnz** [comment]
Hey Dan! Sorry about the delay. There has been an update to Lob's API with how metrics are gathered. I will make the correction to older versions of Address Elements. In the meantime, please use latest version of Address Elements here:

https://cdn.lob.com/lob/address-elements/2.2.1/address-elements.min.js

Thank you for bringing this to my attention!

**Comment by dan714** [comment]
No worries and thanks for the fix! That seems to have worked.
